dbdata:
  image: postgres:9.4
  command: true
dbbackup:
  image: alpine
  volumes_from:
    - dbdata
  command: true
db:
  build: postgres
  volumes_from:
    - dbdata
matchmaker:
  build: matchmaker
  volumes:
    - matchmaker:/usr/src/app
    - matchlog:/var/log/robot/matches
  links:
    - db
  command: './matchmaker.py'
webapp:
  build: webapp
  volumes:
    - webapp:/usr/src/app
  links:
    - db
server:
  image: nginx:1.9
  volumes:
    - static:/usr/local/static
    - matchlog:/usr/local/matchlog
    - nginx:/etc/nginx/conf.d
  ports:
    - "80:80"
  links:
    - webapp
